<?php

declare(strict_types=1);

namespace tests\Auth;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use WScore\Auth\Auth;
use WScore\Auth\UserAdaptor\UserPasswd;

require_once dirname(__DIR__) . '/autoloader.php';

class HtpasswdUserList_Test extends TestCase
{
    #[Test]
    public function plain_text_password_is_not_accepted_for_htpasswd_user_list(): void
    {
        $htpasswd = $this->makeTempFile("plain:pw\n");
        $provider = UserPasswd::fromHtpasswd($htpasswd);
        $auth = new Auth($provider);

        $this->assertFalse($auth->loginWithPassword('plain', 'pw'));
    }

    #[Test]
    public function login_successful_with_bcrypt_hash_from_htpasswd(): void
    {
        $hash = password_hash('test-PW', PASSWORD_BCRYPT);
        $this->assertIsString($hash);
        $this->assertNotSame('', $hash);

        $htpasswd = $this->makeTempFile("test:{$hash}\n");
        $provider = UserPasswd::fromHtpasswd($htpasswd);
        $auth = new Auth($provider);

        $this->assertTrue($auth->loginWithPassword('test', 'test-PW'));
        $this->assertSame('test', $auth->getLoginId());
    }

    #[Test]
    public function login_fails_with_wrong_password_for_htpasswd_user(): void
    {
        $hash = password_hash('test-PW', PASSWORD_BCRYPT);
        $htpasswd = $this->makeTempFile("test:{$hash}\n");
        $provider = UserPasswd::fromHtpasswd($htpasswd);
        $auth = new Auth($provider);

        $this->assertFalse($auth->loginWithPassword('test', 'wrong'));
    }

    #[Test]
    public function login_successful_with_sha1_format_from_htpasswd(): void
    {
        $sha = base64_encode(sha1('pw', true));
        $htpasswd = $this->makeTempFile("alice:{SHA}{$sha}\n");
        $provider = UserPasswd::fromHtpasswd($htpasswd);
        $auth = new Auth($provider);

        $this->assertTrue($auth->loginWithPassword('alice', 'pw'));
    }

    #[Test]
    public function login_successful_with_apr1_md5_from_htpasswd(): void
    {
        // generated by: `openssl passwd -apr1 -salt salt pw`
        $apr1 = '$apr1$salt$dIQSC7CZVMfwYUarWFsjy0';
        $htpasswd = $this->makeTempFile("md5user:{$apr1}\n");
        $provider = UserPasswd::fromHtpasswd($htpasswd);
        $auth = new Auth($provider);

        $this->assertTrue($auth->loginWithPassword('md5user', 'pw'));
    }

    #[Test]
    public function fromHtaccess_resolves_authuserfile_and_authenticates(): void
    {
        $hash = password_hash('pw', PASSWORD_BCRYPT);
        $htpasswd = $this->makeTempFile("bob:{$hash}\n");

        $htaccess = $this->makeTempFile("AuthUserFile {$htpasswd}\n");

        $provider = UserPasswd::fromHtaccess($htaccess);
        $auth = new Auth($provider);

        $this->assertTrue($auth->loginWithPassword('bob', 'pw'));
    }

    private function makeTempFile(string $contents): string
    {
        $path = tempnam(sys_get_temp_dir(), 'wsauth_');
        $this->assertIsString($path);
        $this->assertNotSame('', $path);
        file_put_contents($path, $contents);

        return $path;
    }
}

